
[[pages]]
path = "app.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/resume_analyzer.py"
name = "Resume Analyzer"
icon = "ğŸ“„"

[[pages]]
path = "pages/settings.py"
name = "Settings"
icon = "âš™ï¸"

[[pages]]
path = "pages/tips_and_guide.py"
name = "Tips And Guide"
icon = "ğŸ’¡"
